export enum CapabilityStatus {
  IMPLEMENTED = 'IMPLEMENTED',
  PARTIAL = 'PARTIAL',
  BEHIND_FEATURE_FLAG = 'BEHIND_FEATURE_FLAG',
  REQUIRES_CONFIGURATION = 'REQUIRES_CONFIGURATION',
  ROADMAP = 'ROADMAP',
  DISABLED = 'DISABLED',
}
