export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
}

export enum InvoiceDocumentType {
  FACTURA_ELECTRONICA = 'FACTURA_ELECTRONICA',
  TIQUETE_ELECTRONICO = 'TIQUETE_ELECTRONICO',
  NOTA_CREDITO = 'NOTA_CREDITO',
  NOTA_DEBITO = 'NOTA_DEBITO',
  MENSAJE_RECEPTOR = 'MENSAJE_RECEPTOR',
}

export enum InvoiceIssuanceMode {
  MANUAL_ONLY = 'MANUAL_ONLY',
  HACIENDA = 'HACIENDA',
}

export enum HaciendaStatus {
  DRAFT = 'DRAFT',
  PENDING_SUBMISSION = 'PENDING_SUBMISSION',
  SUBMITTED = 'SUBMITTED',
  RECIBIDO = 'RECIBIDO',
  PROCESANDO = 'PROCESANDO',
  ACEPTADO = 'ACEPTADO',
  RECHAZADO = 'RECHAZADO',
  ERROR = 'ERROR',
}
