name = "pymeshubsaas"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[vars]
API_URL = "https://api.pymeshub.lat"
VITE_API_URL = "https://api.pymeshub.lat"
OPENAI_AGENT_WORKFLOW_ID = "wf_69ee50a4431881908f0c86097bc88c0b0e1d93fe68eecbd2"
VITE_PADDLE_CLIENT_TOKEN = "test_5e8c6bb9ac0caa99c0d4d7675f4"
VITE_PADDLE_ENVIRONMENT = "sandbox"
VITE_PADDLE_PRICE_STARTER_MONTHLY = "pri_01kq0w7bt8n3hdyayate39wrvx"
VITE_PADDLE_PRICE_STARTER_ANNUAL = "pri_01kq1c25yej2mxjvjn07fhv2fw"
VITE_PADDLE_PRICE_GROWTH_MONTHLY = "pri_01kq0we4j1wf2pgmh3w14arc6c"
VITE_PADDLE_PRICE_GROWTH_ANNUAL = "pri_01kq1bqs2v3hkx3d0mx4wkxsvg"
VITE_PADDLE_PRICE_ENTERPRISE_MONTHLY = "pri_01kq0wjzkyncpwaj33m1fppppj"
VITE_PADDLE_PRICE_ENTERPRISE_ANNUAL = "pri_01kq1bgffcm5jp82ytctx9necr"
VITE_PADDLE_PRICE_AI_ASSISTANT_MONTHLY = "pri_01kqdhgewjpryvfxen9e6xs30j"
VITE_PADDLE_PRICE_AI_ASSISTANT_ANNUAL = "pri_01kqdhv10gq2h354ba8tmw9px0"

[assets]
directory = "./apps/web/dist/public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
