ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "subtotal" DECIMAL(12,2);
ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "tax_rate" DECIMAL(5,2);
ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "tax_amount" DECIMAL(12,2);
