-- The platform category taxonomy: 18 sectors, each with the categories it holds.
--
-- Rows rather than code. `category` already has a `parent_id` whose own comment says what
-- the shape is — "two levels at most: a parent is a grouping, not a tree" — so a taxonomy
-- belongs in the table and not in a constant in either client. Every screen that draws a
-- category reads `catalog.categories`, and after this migration what it reads is a list
-- nobody has to edit a file to change.
--
-- Slugs are derived from the names with the same folding `admin.saveCategory` applies, and
-- the three names that appear under two sectors — Flooring, Storage & Organization, Gaming
-- / Esports — carry their sector in the slug, because `category_slug_unique` is one index
-- over the whole table rather than one per parent.
--
-- `icon_name` is set for the 18 sectors and left NULL for the rest. The column is an
-- **Ionicons** name and `apps/mobile` casts it straight at the glyph map, so a name from
-- another set draws a tofu box rather than nothing — see `packages/db/src/seed.ts`. NULL is
-- the honest value for a category nobody has chosen a glyph for: `lib/category-icon.ts`
-- falls back to `pricetag-outline` for it silently, where a wrong name would be a defect on
-- a screen.
--
-- `INSERT OR IGNORE` so a database that already holds one of these slugs — a developer who
-- seeded before this migration existed — keeps its own row instead of failing the apply.

INSERT OR IGNORE INTO `category` (`id`, `slug`, `name`, `icon_name`, `image_url`, `parent_id`, `sort_order`, `is_active`) VALUES
  ('cat_food-beverage', 'food-beverage', 'Food & Beverage', 'restaurant-outline', NULL, NULL, 100, 1),
  ('cat_groceries', 'groceries', 'Groceries', NULL, NULL, 'cat_food-beverage', 101, 1),
  ('cat_beverages', 'beverages', 'Beverages', NULL, NULL, 'cat_food-beverage', 102, 1),
  ('cat_delicatessen-specialty', 'delicatessen-specialty', 'Delicatessen / Specialty', NULL, NULL, 'cat_food-beverage', 103, 1),
  ('cat_confectionery', 'confectionery', 'Confectionery', NULL, NULL, 'cat_food-beverage', 104, 1),
  ('cat_food-service', 'food-service', 'Food Service', NULL, NULL, 'cat_food-beverage', 105, 1),
  ('cat_snacks-convenience', 'snacks-convenience', 'Snacks & Convenience', NULL, NULL, 'cat_food-beverage', 106, 1),
  ('cat_health-foods', 'health-foods', 'Health Foods', NULL, NULL, 'cat_food-beverage', 107, 1),
  ('cat_butcher-fishmonger', 'butcher-fishmonger', 'Butcher / Fishmonger', NULL, NULL, 'cat_food-beverage', 108, 1),
  ('cat_bakery', 'bakery', 'Bakery', NULL, NULL, 'cat_food-beverage', 109, 1),
  ('cat_dairy', 'dairy', 'Dairy', NULL, NULL, 'cat_food-beverage', 110, 1),
  ('cat_clothing-fashion', 'clothing-fashion', 'Clothing & Fashion', 'shirt-outline', NULL, NULL, 200, 1),
  ('cat_menswear', 'menswear', 'Menswear', NULL, NULL, 'cat_clothing-fashion', 201, 1),
  ('cat_womenswear', 'womenswear', 'Womenswear', NULL, NULL, 'cat_clothing-fashion', 202, 1),
  ('cat_children-s-infants', 'children-s-infants', 'Children''s / Infants', NULL, NULL, 'cat_clothing-fashion', 203, 1),
  ('cat_footwear', 'footwear', 'Footwear', NULL, NULL, 'cat_clothing-fashion', 204, 1),
  ('cat_accessories', 'accessories', 'Accessories', NULL, NULL, 'cat_clothing-fashion', 205, 1),
  ('cat_lingerie-swimwear', 'lingerie-swimwear', 'Lingerie / Swimwear', NULL, NULL, 'cat_clothing-fashion', 206, 1),
  ('cat_bridal-formal', 'bridal-formal', 'Bridal / Formal', NULL, NULL, 'cat_clothing-fashion', 207, 1),
  ('cat_workwear-uniforms', 'workwear-uniforms', 'Workwear / Uniforms', NULL, NULL, 'cat_clothing-fashion', 208, 1),
  ('cat_sportswear-activewear', 'sportswear-activewear', 'Sportswear / Activewear', NULL, NULL, 'cat_clothing-fashion', 209, 1),
  ('cat_outerwear', 'outerwear', 'Outerwear', NULL, NULL, 'cat_clothing-fashion', 210, 1),
  ('cat_knitwear', 'knitwear', 'Knitwear', NULL, NULL, 'cat_clothing-fashion', 211, 1),
  ('cat_leather-goods', 'leather-goods', 'Leather Goods', NULL, NULL, 'cat_clothing-fashion', 212, 1),
  ('cat_maternity', 'maternity', 'Maternity', NULL, NULL, 'cat_clothing-fashion', 213, 1),
  ('cat_schoolwear', 'schoolwear', 'Schoolwear', NULL, NULL, 'cat_clothing-fashion', 214, 1),
  ('cat_electronics-technology', 'electronics-technology', 'Electronics & Technology', 'hardware-chip-outline', NULL, NULL, 300, 1),
  ('cat_consumer-electronics', 'consumer-electronics', 'Consumer Electronics', NULL, NULL, 'cat_electronics-technology', 301, 1),
  ('cat_computers-peripherals', 'computers-peripherals', 'Computers & Peripherals', NULL, NULL, 'cat_electronics-technology', 302, 1),
  ('cat_mobile-devices', 'mobile-devices', 'Mobile Devices', NULL, NULL, 'cat_electronics-technology', 303, 1),
  ('cat_gaming', 'gaming', 'Gaming', NULL, NULL, 'cat_electronics-technology', 304, 1),
  ('cat_cameras-photography', 'cameras-photography', 'Cameras & Photography', NULL, NULL, 'cat_electronics-technology', 305, 1),
  ('cat_audio', 'audio', 'Audio', NULL, NULL, 'cat_electronics-technology', 306, 1),
  ('cat_smart-home', 'smart-home', 'Smart Home', NULL, NULL, 'cat_electronics-technology', 307, 1),
  ('cat_networking', 'networking', 'Networking', NULL, NULL, 'cat_electronics-technology', 308, 1),
  ('cat_software-digital-content', 'software-digital-content', 'Software & Digital Content', NULL, NULL, 'cat_electronics-technology', 309, 1),
  ('cat_office-technology', 'office-technology', 'Office Technology', NULL, NULL, 'cat_electronics-technology', 310, 1),
  ('cat_it-services', 'it-services', 'IT Services', NULL, NULL, 'cat_electronics-technology', 311, 1),
  ('cat_telecom-isps', 'telecom-isps', 'Telecom / ISPs', NULL, NULL, 'cat_electronics-technology', 312, 1),
  ('cat_home-furniture-decor', 'home-furniture-decor', 'Home, Furniture & Décor', 'home-outline', NULL, NULL, 400, 1),
  ('cat_furniture', 'furniture', 'Furniture', NULL, NULL, 'cat_home-furniture-decor', 401, 1),
  ('cat_home-decor', 'home-decor', 'Home Décor', NULL, NULL, 'cat_home-furniture-decor', 402, 1),
  ('cat_bedding-linens', 'bedding-linens', 'Bedding & Linens', NULL, NULL, 'cat_home-furniture-decor', 403, 1),
  ('cat_kitchen-dining', 'kitchen-dining', 'Kitchen & Dining', NULL, NULL, 'cat_home-furniture-decor', 404, 1),
  ('cat_bath', 'bath', 'Bath', NULL, NULL, 'cat_home-furniture-decor', 405, 1),
  ('cat_lighting', 'lighting', 'Lighting', NULL, NULL, 'cat_home-furniture-decor', 406, 1),
  ('cat_window-treatments', 'window-treatments', 'Window Treatments', NULL, NULL, 'cat_home-furniture-decor', 407, 1),
  ('cat_flooring', 'flooring', 'Flooring', NULL, NULL, 'cat_home-furniture-decor', 408, 1),
  ('cat_paint-wall-covering', 'paint-wall-covering', 'Paint & Wall Covering', NULL, NULL, 'cat_home-furniture-decor', 409, 1),
  ('cat_home-textiles', 'home-textiles', 'Home Textiles', NULL, NULL, 'cat_home-furniture-decor', 410, 1),
  ('cat_appliances', 'appliances', 'Appliances', NULL, NULL, 'cat_home-furniture-decor', 411, 1),
  ('cat_fireplaces-heating', 'fireplaces-heating', 'Fireplaces & Heating', NULL, NULL, 'cat_home-furniture-decor', 412, 1),
  ('cat_storage-organization', 'storage-organization', 'Storage & Organization', NULL, NULL, 'cat_home-furniture-decor', 413, 1),
  ('cat_mattresses-sleep', 'mattresses-sleep', 'Mattresses & Sleep', NULL, NULL, 'cat_home-furniture-decor', 414, 1),
  ('cat_beauty-health-personal-care', 'beauty-health-personal-care', 'Beauty, Health & Personal Care', 'sparkles-outline', NULL, NULL, 500, 1),
  ('cat_cosmetics', 'cosmetics', 'Cosmetics', NULL, NULL, 'cat_beauty-health-personal-care', 501, 1),
  ('cat_skincare', 'skincare', 'Skincare', NULL, NULL, 'cat_beauty-health-personal-care', 502, 1),
  ('cat_hair-care', 'hair-care', 'Hair Care', NULL, NULL, 'cat_beauty-health-personal-care', 503, 1),
  ('cat_fragrance', 'fragrance', 'Fragrance', NULL, NULL, 'cat_beauty-health-personal-care', 504, 1),
  ('cat_grooming', 'grooming', 'Grooming', NULL, NULL, 'cat_beauty-health-personal-care', 505, 1),
  ('cat_oral-care', 'oral-care', 'Oral Care', NULL, NULL, 'cat_beauty-health-personal-care', 506, 1),
  ('cat_pharmacy-otc', 'pharmacy-otc', 'Pharmacy / OTC', NULL, NULL, 'cat_beauty-health-personal-care', 507, 1),
  ('cat_medical-devices', 'medical-devices', 'Medical Devices', NULL, NULL, 'cat_beauty-health-personal-care', 508, 1),
  ('cat_hearing-aids', 'hearing-aids', 'Hearing Aids', NULL, NULL, 'cat_beauty-health-personal-care', 509, 1),
  ('cat_orthopedic', 'orthopedic', 'Orthopedic', NULL, NULL, 'cat_beauty-health-personal-care', 510, 1),
  ('cat_vitamins-supplements', 'vitamins-supplements', 'Vitamins & Supplements', NULL, NULL, 'cat_beauty-health-personal-care', 511, 1),
  ('cat_sexual-wellness', 'sexual-wellness', 'Sexual Wellness', NULL, NULL, 'cat_beauty-health-personal-care', 512, 1),
  ('cat_spas-aesthetics', 'spas-aesthetics', 'Spas & Aesthetics', NULL, NULL, 'cat_beauty-health-personal-care', 513, 1),
  ('cat_medical-dental-services', 'medical-dental-services', 'Medical / Dental Services', NULL, NULL, 'cat_beauty-health-personal-care', 514, 1),
  ('cat_mental-health', 'mental-health', 'Mental Health', NULL, NULL, 'cat_beauty-health-personal-care', 515, 1),
  ('cat_sports-outdoors-recreation', 'sports-outdoors-recreation', 'Sports, Outdoors & Recreation', 'barbell-outline', NULL, NULL, 600, 1),
  ('cat_fitness-equipment', 'fitness-equipment', 'Fitness Equipment', NULL, NULL, 'cat_sports-outdoors-recreation', 601, 1),
  ('cat_camping-hiking', 'camping-hiking', 'Camping & Hiking', NULL, NULL, 'cat_sports-outdoors-recreation', 602, 1),
  ('cat_fishing', 'fishing', 'Fishing', NULL, NULL, 'cat_sports-outdoors-recreation', 603, 1),
  ('cat_hunting', 'hunting', 'Hunting', NULL, NULL, 'cat_sports-outdoors-recreation', 604, 1),
  ('cat_water-sports', 'water-sports', 'Water Sports', NULL, NULL, 'cat_sports-outdoors-recreation', 605, 1),
  ('cat_winter-sports', 'winter-sports', 'Winter Sports', NULL, NULL, 'cat_sports-outdoors-recreation', 606, 1),
  ('cat_cycling', 'cycling', 'Cycling', NULL, NULL, 'cat_sports-outdoors-recreation', 607, 1),
  ('cat_team-sports', 'team-sports', 'Team Sports', NULL, NULL, 'cat_sports-outdoors-recreation', 608, 1),
  ('cat_golf', 'golf', 'Golf', NULL, NULL, 'cat_sports-outdoors-recreation', 609, 1),
  ('cat_martial-arts-combat', 'martial-arts-combat', 'Martial Arts / Combat', NULL, NULL, 'cat_sports-outdoors-recreation', 610, 1),
  ('cat_climbing-mountaineering', 'climbing-mountaineering', 'Climbing & Mountaineering', NULL, NULL, 'cat_sports-outdoors-recreation', 611, 1),
  ('cat_parks-attractions', 'parks-attractions', 'Parks & Attractions', NULL, NULL, 'cat_sports-outdoors-recreation', 612, 1),
  ('cat_golf-courses-country-clubs', 'golf-courses-country-clubs', 'Golf Courses / Country Clubs', NULL, NULL, 'cat_sports-outdoors-recreation', 613, 1),
  ('cat_sports-clubs-gyms', 'sports-clubs-gyms', 'Sports Clubs / Gyms', NULL, NULL, 'cat_sports-outdoors-recreation', 614, 1),
  ('cat_automotive', 'automotive', 'Automotive', 'car-outline', NULL, NULL, 700, 1),
  ('cat_new-vehicles', 'new-vehicles', 'New Vehicles', NULL, NULL, 'cat_automotive', 701, 1),
  ('cat_used-vehicles', 'used-vehicles', 'Used Vehicles', NULL, NULL, 'cat_automotive', 702, 1),
  ('cat_parts-accessories', 'parts-accessories', 'Parts & Accessories', NULL, NULL, 'cat_automotive', 703, 1),
  ('cat_auto-service-repair', 'auto-service-repair', 'Auto Service & Repair', NULL, NULL, 'cat_automotive', 704, 1),
  ('cat_body-paint', 'body-paint', 'Body & Paint', NULL, NULL, 'cat_automotive', 705, 1),
  ('cat_fuel-charging', 'fuel-charging', 'Fuel & Charging', NULL, NULL, 'cat_automotive', 706, 1),
  ('cat_car-wash-detailing', 'car-wash-detailing', 'Car Wash / Detailing', NULL, NULL, 'cat_automotive', 707, 1),
  ('cat_towing-roadside', 'towing-roadside', 'Towing & Roadside', NULL, NULL, 'cat_automotive', 708, 1),
  ('cat_auto-insurance', 'auto-insurance', 'Auto Insurance', NULL, NULL, 'cat_automotive', 709, 1),
  ('cat_parking', 'parking', 'Parking', NULL, NULL, 'cat_automotive', 710, 1),
  ('cat_motorcycles-atvs-powersports', 'motorcycles-atvs-powersports', 'Motorcycles / ATVs / Powersports', NULL, NULL, 'cat_automotive', 711, 1),
  ('cat_marine-boats', 'marine-boats', 'Marine / Boats', NULL, NULL, 'cat_automotive', 712, 1),
  ('cat_rv-recreational', 'rv-recreational', 'RV / Recreational', NULL, NULL, 'cat_automotive', 713, 1),
  ('cat_racing-performance', 'racing-performance', 'Racing / Performance', NULL, NULL, 'cat_automotive', 714, 1),
  ('cat_toys-hobbies-collectibles', 'toys-hobbies-collectibles', 'Toys, Hobbies & Collectibles', 'game-controller-outline', NULL, NULL, 800, 1),
  ('cat_toys', 'toys', 'Toys', NULL, NULL, 'cat_toys-hobbies-collectibles', 801, 1),
  ('cat_model-kits', 'model-kits', 'Model Kits', NULL, NULL, 'cat_toys-hobbies-collectibles', 802, 1),
  ('cat_collectibles', 'collectibles', 'Collectibles', NULL, NULL, 'cat_toys-hobbies-collectibles', 803, 1),
  ('cat_arts-crafts', 'arts-crafts', 'Arts & Crafts', NULL, NULL, 'cat_toys-hobbies-collectibles', 804, 1),
  ('cat_hobby-shops', 'hobby-shops', 'Hobby Shops', NULL, NULL, 'cat_toys-hobbies-collectibles', 805, 1),
  ('cat_card-games-board-games', 'card-games-board-games', 'Card Games / Board Games', NULL, NULL, 'cat_toys-hobbies-collectibles', 806, 1),
  ('cat_puzzles-brain-games', 'puzzles-brain-games', 'Puzzles & Brain Games', NULL, NULL, 'cat_toys-hobbies-collectibles', 807, 1),
  ('cat_musical-instruments', 'musical-instruments', 'Musical Instruments', NULL, NULL, 'cat_toys-hobbies-collectibles', 808, 1),
  ('cat_photography-film', 'photography-film', 'Photography / Film', NULL, NULL, 'cat_toys-hobbies-collectibles', 809, 1),
  ('cat_video-games-gaming', 'video-games-gaming', 'Video Games / Gaming', NULL, NULL, 'cat_toys-hobbies-collectibles', 810, 1),
  ('cat_books-media-entertainment', 'books-media-entertainment', 'Books, Media & Entertainment', 'book-outline', NULL, NULL, 900, 1),
  ('cat_books', 'books', 'Books', NULL, NULL, 'cat_books-media-entertainment', 901, 1),
  ('cat_magazines-newspapers', 'magazines-newspapers', 'Magazines / Newspapers', NULL, NULL, 'cat_books-media-entertainment', 902, 1),
  ('cat_music', 'music', 'Music', NULL, NULL, 'cat_books-media-entertainment', 903, 1),
  ('cat_film-tv', 'film-tv', 'Film / TV', NULL, NULL, 'cat_books-media-entertainment', 904, 1),
  ('cat_art-galleries', 'art-galleries', 'Art & Galleries', NULL, NULL, 'cat_books-media-entertainment', 905, 1),
  ('cat_ticketing-events', 'ticketing-events', 'Ticketing / Events', NULL, NULL, 'cat_books-media-entertainment', 906, 1),
  ('cat_streaming-subscriptions', 'streaming-subscriptions', 'Streaming / Subscriptions', NULL, NULL, 'cat_books-media-entertainment', 907, 1),
  ('cat_gaming-esports', 'gaming-esports', 'Gaming / Esports', NULL, NULL, 'cat_books-media-entertainment', 908, 1),
  ('cat_lotteries-gambling', 'lotteries-gambling', 'Lotteries / Gambling', NULL, NULL, 'cat_books-media-entertainment', 909, 1),
  ('cat_pet-supplies-services', 'pet-supplies-services', 'Pet Supplies & Services', 'paw-outline', NULL, NULL, 1000, 1),
  ('cat_pet-food', 'pet-food', 'Pet Food', NULL, NULL, 'cat_pet-supplies-services', 1001, 1),
  ('cat_pet-toys-accessories', 'pet-toys-accessories', 'Pet Toys & Accessories', NULL, NULL, 'cat_pet-supplies-services', 1002, 1),
  ('cat_pet-health', 'pet-health', 'Pet Health', NULL, NULL, 'cat_pet-supplies-services', 1003, 1),
  ('cat_veterinary-services', 'veterinary-services', 'Veterinary Services', NULL, NULL, 'cat_pet-supplies-services', 1004, 1),
  ('cat_pet-grooming', 'pet-grooming', 'Pet Grooming', NULL, NULL, 'cat_pet-supplies-services', 1005, 1),
  ('cat_pet-boarding-daycare', 'pet-boarding-daycare', 'Pet Boarding / Daycare', NULL, NULL, 'cat_pet-supplies-services', 1006, 1),
  ('cat_pet-training', 'pet-training', 'Pet Training', NULL, NULL, 'cat_pet-supplies-services', 1007, 1),
  ('cat_exotic-special', 'exotic-special', 'Exotic / Special', NULL, NULL, 'cat_pet-supplies-services', 1008, 1),
  ('cat_equestrian', 'equestrian', 'Equestrian', NULL, NULL, 'cat_pet-supplies-services', 1009, 1),
  ('cat_garden-diy-home-improvement', 'garden-diy-home-improvement', 'Garden, DIY & Home Improvement', 'leaf-outline', NULL, NULL, 1100, 1),
  ('cat_garden-landscaping', 'garden-landscaping', 'Garden / Landscaping', NULL, NULL, 'cat_garden-diy-home-improvement', 1101, 1),
  ('cat_hardware', 'hardware', 'Hardware', NULL, NULL, 'cat_garden-diy-home-improvement', 1102, 1),
  ('cat_plumbing', 'plumbing', 'Plumbing', NULL, NULL, 'cat_garden-diy-home-improvement', 1103, 1),
  ('cat_electrical', 'electrical', 'Electrical', NULL, NULL, 'cat_garden-diy-home-improvement', 1104, 1),
  ('cat_lumber-building-materials', 'lumber-building-materials', 'Lumber / Building Materials', NULL, NULL, 'cat_garden-diy-home-improvement', 1105, 1),
  ('cat_paint-supplies', 'paint-supplies', 'Paint & Supplies', NULL, NULL, 'cat_garden-diy-home-improvement', 1106, 1),
  ('cat_flooring-garden-diy-home-improvement', 'flooring-garden-diy-home-improvement', 'Flooring', NULL, NULL, 'cat_garden-diy-home-improvement', 1107, 1),
  ('cat_windows-doors', 'windows-doors', 'Windows & Doors', NULL, NULL, 'cat_garden-diy-home-improvement', 1108, 1),
  ('cat_appliances-diy', 'appliances-diy', 'Appliances (DIY)', NULL, NULL, 'cat_garden-diy-home-improvement', 1109, 1),
  ('cat_pool-spa', 'pool-spa', 'Pool & Spa', NULL, NULL, 'cat_garden-diy-home-improvement', 1110, 1),
  ('cat_outdoor-living', 'outdoor-living', 'Outdoor Living', NULL, NULL, 'cat_garden-diy-home-improvement', 1111, 1),
  ('cat_tools-power', 'tools-power', 'Tools (Power)', NULL, NULL, 'cat_garden-diy-home-improvement', 1112, 1),
  ('cat_safety-security', 'safety-security', 'Safety / Security', NULL, NULL, 'cat_garden-diy-home-improvement', 1113, 1),
  ('cat_office-stationery-business-supplies', 'office-stationery-business-supplies', 'Office, Stationery & Business Supplies', 'briefcase-outline', NULL, NULL, 1200, 1),
  ('cat_paper-writing', 'paper-writing', 'Paper & Writing', NULL, NULL, 'cat_office-stationery-business-supplies', 1201, 1),
  ('cat_office-furniture', 'office-furniture', 'Office Furniture', NULL, NULL, 'cat_office-stationery-business-supplies', 1202, 1),
  ('cat_print-copy', 'print-copy', 'Print / Copy', NULL, NULL, 'cat_office-stationery-business-supplies', 1203, 1),
  ('cat_storage-organization-office-stationery-business-supplies', 'storage-organization-office-stationery-business-supplies', 'Storage & Organization', NULL, NULL, 'cat_office-stationery-business-supplies', 1204, 1),
  ('cat_tech-av', 'tech-av', 'Tech / AV', NULL, NULL, 'cat_office-stationery-business-supplies', 1205, 1),
  ('cat_mailing-shipping', 'mailing-shipping', 'Mailing / Shipping', NULL, NULL, 'cat_office-stationery-business-supplies', 1206, 1),
  ('cat_business-services', 'business-services', 'Business Services', NULL, NULL, 'cat_office-stationery-business-supplies', 1207, 1),
  ('cat_printing-signage', 'printing-signage', 'Printing / Signage', NULL, NULL, 'cat_office-stationery-business-supplies', 1208, 1),
  ('cat_janitorial-cleaning', 'janitorial-cleaning', 'Janitorial / Cleaning', NULL, NULL, 'cat_office-stationery-business-supplies', 1209, 1),
  ('cat_uniforms-workwear', 'uniforms-workwear', 'Uniforms / Workwear', NULL, NULL, 'cat_office-stationery-business-supplies', 1210, 1),
  ('cat_jewelry-watches-luxury', 'jewelry-watches-luxury', 'Jewelry, Watches & Luxury', 'diamond-outline', NULL, NULL, 1300, 1),
  ('cat_fine-jewelry', 'fine-jewelry', 'Fine Jewelry', NULL, NULL, 'cat_jewelry-watches-luxury', 1301, 1),
  ('cat_fashion-jewelry', 'fashion-jewelry', 'Fashion Jewelry', NULL, NULL, 'cat_jewelry-watches-luxury', 1302, 1),
  ('cat_watches', 'watches', 'Watches', NULL, NULL, 'cat_jewelry-watches-luxury', 1303, 1),
  ('cat_luxury-bags-handbags', 'luxury-bags-handbags', 'Luxury Bags / Handbags', NULL, NULL, 'cat_jewelry-watches-luxury', 1304, 1),
  ('cat_eyewear', 'eyewear', 'Eyewear', NULL, NULL, 'cat_jewelry-watches-luxury', 1305, 1),
  ('cat_cigars-tobacco', 'cigars-tobacco', 'Cigars / Tobacco', NULL, NULL, 'cat_jewelry-watches-luxury', 1306, 1),
  ('cat_fragrance-luxury', 'fragrance-luxury', 'Fragrance (Luxury)', NULL, NULL, 'cat_jewelry-watches-luxury', 1307, 1),
  ('cat_art-collectibles', 'art-collectibles', 'Art / Collectibles', NULL, NULL, 'cat_jewelry-watches-luxury', 1308, 1),
  ('cat_luxury-cars-yachts', 'luxury-cars-yachts', 'Luxury Cars / Yachts', NULL, NULL, 'cat_jewelry-watches-luxury', 1309, 1),
  ('cat_travel-hospitality-tourism', 'travel-hospitality-tourism', 'Travel, Hospitality & Tourism', 'airplane-outline', NULL, NULL, 1400, 1),
  ('cat_hotels-resorts', 'hotels-resorts', 'Hotels / Resorts', NULL, NULL, 'cat_travel-hospitality-tourism', 1401, 1),
  ('cat_airlines-flights', 'airlines-flights', 'Airlines / Flights', NULL, NULL, 'cat_travel-hospitality-tourism', 1402, 1),
  ('cat_car-rental', 'car-rental', 'Car Rental', NULL, NULL, 'cat_travel-hospitality-tourism', 1403, 1),
  ('cat_cruise-lines', 'cruise-lines', 'Cruise Lines', NULL, NULL, 'cat_travel-hospitality-tourism', 1404, 1),
  ('cat_travel-agencies-tours', 'travel-agencies-tours', 'Travel Agencies / Tours', NULL, NULL, 'cat_travel-hospitality-tourism', 1405, 1),
  ('cat_ground-transport', 'ground-transport', 'Ground Transport', NULL, NULL, 'cat_travel-hospitality-tourism', 1406, 1),
  ('cat_camping-rv-parks', 'camping-rv-parks', 'Camping / RV Parks', NULL, NULL, 'cat_travel-hospitality-tourism', 1407, 1),
  ('cat_timeshares-vacation-ownership', 'timeshares-vacation-ownership', 'Timeshares / Vacation Ownership', NULL, NULL, 'cat_travel-hospitality-tourism', 1408, 1),
  ('cat_travel-insurance', 'travel-insurance', 'Travel Insurance', NULL, NULL, 'cat_travel-hospitality-tourism', 1409, 1),
  ('cat_duty-free-airport-retail', 'duty-free-airport-retail', 'Duty-Free / Airport Retail', NULL, NULL, 'cat_travel-hospitality-tourism', 1410, 1),
  ('cat_financial-insurance-services', 'financial-insurance-services', 'Financial & Insurance Services', 'card-outline', NULL, NULL, 1500, 1),
  ('cat_banking', 'banking', 'Banking', NULL, NULL, 'cat_financial-insurance-services', 1501, 1),
  ('cat_credit-cards', 'credit-cards', 'Credit Cards', NULL, NULL, 'cat_financial-insurance-services', 1502, 1),
  ('cat_insurance', 'insurance', 'Insurance', NULL, NULL, 'cat_financial-insurance-services', 1503, 1),
  ('cat_investment-brokerage', 'investment-brokerage', 'Investment / Brokerage', NULL, NULL, 'cat_financial-insurance-services', 1504, 1),
  ('cat_wealth-management', 'wealth-management', 'Wealth Management', NULL, NULL, 'cat_financial-insurance-services', 1505, 1),
  ('cat_money-transfer-remittance', 'money-transfer-remittance', 'Money Transfer / Remittance', NULL, NULL, 'cat_financial-insurance-services', 1506, 1),
  ('cat_payment-services', 'payment-services', 'Payment Services', NULL, NULL, 'cat_financial-insurance-services', 1507, 1),
  ('cat_government-taxes', 'government-taxes', 'Government / Taxes', NULL, NULL, 'cat_financial-insurance-services', 1508, 1),
  ('cat_real-estate', 'real-estate', 'Real Estate', NULL, NULL, 'cat_financial-insurance-services', 1509, 1),
  ('cat_legal', 'legal', 'Legal', NULL, NULL, 'cat_financial-insurance-services', 1510, 1),
  ('cat_education-training', 'education-training', 'Education & Training', 'school-outline', NULL, NULL, 1600, 1),
  ('cat_k-12', 'k-12', 'K-12', NULL, NULL, 'cat_education-training', 1601, 1),
  ('cat_higher-education', 'higher-education', 'Higher Education', NULL, NULL, 'cat_education-training', 1602, 1),
  ('cat_vocational-trade', 'vocational-trade', 'Vocational / Trade', NULL, NULL, 'cat_education-training', 1603, 1),
  ('cat_online-learning', 'online-learning', 'Online Learning', NULL, NULL, 'cat_education-training', 1604, 1),
  ('cat_test-prep', 'test-prep', 'Test Prep', NULL, NULL, 'cat_education-training', 1605, 1),
  ('cat_language-music-arts', 'language-music-arts', 'Language / Music / Arts', NULL, NULL, 'cat_education-training', 1606, 1),
  ('cat_corporate-training', 'corporate-training', 'Corporate Training', NULL, NULL, 'cat_education-training', 1607, 1),
  ('cat_books-academic', 'books-academic', 'Books / Academic', NULL, NULL, 'cat_education-training', 1608, 1),
  ('cat_agriculture-industrial-b2b', 'agriculture-industrial-b2b', 'Agriculture, Industrial & B2B', 'construct-outline', NULL, NULL, 1700, 1),
  ('cat_farming-crop', 'farming-crop', 'Farming / Crop', NULL, NULL, 'cat_agriculture-industrial-b2b', 1701, 1),
  ('cat_livestock-poultry', 'livestock-poultry', 'Livestock / Poultry', NULL, NULL, 'cat_agriculture-industrial-b2b', 1702, 1),
  ('cat_fishing-aquaculture', 'fishing-aquaculture', 'Fishing / Aquaculture', NULL, NULL, 'cat_agriculture-industrial-b2b', 1703, 1),
  ('cat_construction-materials', 'construction-materials', 'Construction Materials', NULL, NULL, 'cat_agriculture-industrial-b2b', 1704, 1),
  ('cat_industrial-equipment', 'industrial-equipment', 'Industrial Equipment', NULL, NULL, 'cat_agriculture-industrial-b2b', 1705, 1),
  ('cat_raw-materials', 'raw-materials', 'Raw Materials', NULL, NULL, 'cat_agriculture-industrial-b2b', 1706, 1),
  ('cat_packaging-shipping', 'packaging-shipping', 'Packaging / Shipping', NULL, NULL, 'cat_agriculture-industrial-b2b', 1707, 1),
  ('cat_logistics-freight', 'logistics-freight', 'Logistics / Freight', NULL, NULL, 'cat_agriculture-industrial-b2b', 1708, 1),
  ('cat_energy-utilities', 'energy-utilities', 'Energy / Utilities', NULL, NULL, 'cat_agriculture-industrial-b2b', 1709, 1),
  ('cat_mining-extraction', 'mining-extraction', 'Mining / Extraction', NULL, NULL, 'cat_agriculture-industrial-b2b', 1710, 1),
  ('cat_textile-fabric', 'textile-fabric', 'Textile / Fabric', NULL, NULL, 'cat_agriculture-industrial-b2b', 1711, 1),
  ('cat_chemicals-lab', 'chemicals-lab', 'Chemicals / Lab', NULL, NULL, 'cat_agriculture-industrial-b2b', 1712, 1),
  ('cat_janitorial-commercial', 'janitorial-commercial', 'Janitorial / Commercial', NULL, NULL, 'cat_agriculture-industrial-b2b', 1713, 1),
  ('cat_printing-publishing', 'printing-publishing', 'Printing / Publishing', NULL, NULL, 'cat_agriculture-industrial-b2b', 1714, 1),
  ('cat_miscellaneous-specialty', 'miscellaneous-specialty', 'Miscellaneous & Specialty', 'pricetags-outline', NULL, NULL, 1800, 1),
  ('cat_florists', 'florists', 'Florists', NULL, NULL, 'cat_miscellaneous-specialty', 1801, 1),
  ('cat_gift-novelty-card', 'gift-novelty-card', 'Gift / Novelty / Card', NULL, NULL, 'cat_miscellaneous-specialty', 1802, 1),
  ('cat_religious-goods', 'religious-goods', 'Religious Goods', NULL, NULL, 'cat_miscellaneous-specialty', 1803, 1),
  ('cat_used-secondhand-thrift', 'used-secondhand-thrift', 'Used / Secondhand / Thrift', NULL, NULL, 'cat_miscellaneous-specialty', 1804, 1),
  ('cat_antique-vintage', 'antique-vintage', 'Antique / Vintage', NULL, NULL, 'cat_miscellaneous-specialty', 1805, 1),
  ('cat_pawn-consignment', 'pawn-consignment', 'Pawn / Consignment', NULL, NULL, 'cat_miscellaneous-specialty', 1806, 1),
  ('cat_direct-telemarketing', 'direct-telemarketing', 'Direct / Telemarketing', NULL, NULL, 'cat_miscellaneous-specialty', 1807, 1),
  ('cat_subscription-recurring', 'subscription-recurring', 'Subscription / Recurring', NULL, NULL, 'cat_miscellaneous-specialty', 1808, 1),
  ('cat_pop-up-temporary', 'pop-up-temporary', 'Pop-Up / Temporary', NULL, NULL, 'cat_miscellaneous-specialty', 1809, 1),
  ('cat_auction-bid', 'auction-bid', 'Auction / Bid', NULL, NULL, 'cat_miscellaneous-specialty', 1810, 1),
  ('cat_wrecking-salvage', 'wrecking-salvage', 'Wrecking / Salvage', NULL, NULL, 'cat_miscellaneous-specialty', 1811, 1),
  ('cat_tent-awning-shade', 'tent-awning-shade', 'Tent / Awning / Shade', NULL, NULL, 'cat_miscellaneous-specialty', 1812, 1),
  ('cat_cigar-tobacco', 'cigar-tobacco', 'Cigar / Tobacco', NULL, NULL, 'cat_miscellaneous-specialty', 1813, 1),
  ('cat_news-print', 'news-print', 'News / Print', NULL, NULL, 'cat_miscellaneous-specialty', 1814, 1),
  ('cat_wedding-event', 'wedding-event', 'Wedding / Event', NULL, NULL, 'cat_miscellaneous-specialty', 1815, 1),
  ('cat_funeral-memorial', 'funeral-memorial', 'Funeral / Memorial', NULL, NULL, 'cat_miscellaneous-specialty', 1816, 1),
  ('cat_social-services-nonprofit', 'social-services-nonprofit', 'Social Services / Nonprofit', NULL, NULL, 'cat_miscellaneous-specialty', 1817, 1),
  ('cat_government-public-services', 'government-public-services', 'Government / Public Services', NULL, NULL, 'cat_miscellaneous-specialty', 1818, 1),
  ('cat_adult-intimate', 'adult-intimate', 'Adult / Intimate', NULL, NULL, 'cat_miscellaneous-specialty', 1819, 1),
  ('cat_cannabis-hemp-where-legal', 'cannabis-hemp-where-legal', 'Cannabis / Hemp (where legal)', NULL, NULL, 'cat_miscellaneous-specialty', 1820, 1),
  ('cat_crypto-digital-assets', 'crypto-digital-assets', 'Crypto / Digital Assets', NULL, NULL, 'cat_miscellaneous-specialty', 1821, 1),
  ('cat_3d-printing-makers', '3d-printing-makers', '3D Printing / Makers', NULL, NULL, 'cat_miscellaneous-specialty', 1822, 1),
  ('cat_drones-uavs', 'drones-uavs', 'Drones / UAVs', NULL, NULL, 'cat_miscellaneous-specialty', 1823, 1),
  ('cat_smart-connected-devices', 'smart-connected-devices', 'Smart / Connected Devices', NULL, NULL, 'cat_miscellaneous-specialty', 1824, 1),
  ('cat_sustainable-eco', 'sustainable-eco', 'Sustainable / Eco', NULL, NULL, 'cat_miscellaneous-specialty', 1825, 1),
  ('cat_luxury-concierge', 'luxury-concierge', 'Luxury / Concierge', NULL, NULL, 'cat_miscellaneous-specialty', 1826, 1),
  ('cat_events-entertainment', 'events-entertainment', 'Events / Entertainment', NULL, NULL, 'cat_miscellaneous-specialty', 1827, 1),
  ('cat_gaming-esports-miscellaneous-specialty', 'gaming-esports-miscellaneous-specialty', 'Gaming / Esports', NULL, NULL, 'cat_miscellaneous-specialty', 1828, 1),
  ('cat_virtual-digital-goods', 'virtual-digital-goods', 'Virtual / Digital Goods', NULL, NULL, 'cat_miscellaneous-specialty', 1829, 1)
;--> statement-breakpoint
